name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_INCREMENTAL: 0

jobs:
  clippy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-08
          profile: minimal
          components: clippy, rustc-dev, llvm-tools-preview

      - name: Cache Cargo
        uses: actions/cache@v3.0.5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-clippy-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Clippy
        run: |
          cargo clippy --no-default-features --all-targets -- -D warnings

  tests:
    if: false
    runs-on: macos-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          submodules: recursive

      - name: vcpkg build z3
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: z3
          triplet: x64-osx
          cache-key: macos-latest
          revision: master
          token: ${{ github.token }}
          extra-args: --clean-buildtrees-after-build

      - name: Execute tests
        run: |
          cargo test --all --no-default-features --features=vcpkg -- --test-threads=1
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests"

      - name: Setup grcov
        run: |
          cargo install grcov

      - name: Run grcov
        run: |
          zip -0 cov.zip $(find . -name "mirai*.gc*" -print)
          grcov cov.zip -s . -t lcov --llvm --ignore-not-existing --ignore "/*" -o lcov.info

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "lcov.info"

  mirai_on_mirai_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-08
          profile: minimal
          components: rustc-dev, llvm-tools-preview

      - name: Cache Cargo
        uses: actions/cache@v3.0.5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-mirai-${{ hashFiles('**/Cargo.lock') }}

      - name: Install MIRAI
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force --path ./checker

      - name: Run MIRAI on MIRAI
        run: |
          cargo mirai

  mirai_on_mirai_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-08
          profile: minimal
          components: rustc-dev, llvm-tools-preview

      - name: Cache Cargo
        uses: actions/cache@v3.0.5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-mirai-${{ hashFiles('**/Cargo.lock') }}

      - name: Install MIRAI
        run: |
          cargo install --force --path ./checker

      - name: Run MIRAI on MIRAI
        run: |
          cargo mirai --no-default-features

  mirai_on_mirai_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-08
          profile: minimal
          components: rustc-dev, llvm-tools-preview

      - name: Cache Cargo
        uses: actions/cache@v3.0.5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-mirai-${{ hashFiles('**/Cargo.lock') }}

      - name: Install MIRAI
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force --path ./checker --no-default-features

      - name: Run MIRAI on MIRAI
        run: |
          cargo mirai

